### PR TITLE
#2208 Add interactive dragging to .anytypeSheet

### LINKED ISSUE #2208: Current implementation of anytypeSheet have no interactive drag capabilities
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Current implementation of `.anytypeSheet` used for popup like presentation (object settings for example) have no interactive drag capabilities. It feels quite odd, you still can swipe popup down, but there is no interactivity while doing it.

https://github.com/user-attachments/assets/2d4d1231-82f6-49a6-a688-8887b6f538ef

### Expected Behavior

Something resembling native components

https://github.com/user-attachments/assets/ceb2cea9-7f7a-4cb3-a6c9-2e5d6bc946be

### Steps To Reproduce

Open object/set settings menu

### Environment

```markdown
Any
```

### Anything else?

- AnytypeSheet doesn't need to add the DragIndicator on its own. Clients will add it if applicable.
- Component should support keyboard handling. Swiping when keyboard is visible.
- Drag gesture should work anywhere on the screen and will not conflict with horizontal scrolls inside the screen.
- The size of the content should remain consistent and not shrink during dragging.

### PR DESCRIPTION
**Pull request by stansidel**
---

- [X] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### Description

This PR adds interactive dragging capability to `.anytypeSheet` used for popup like presentation (object settings for example). It should fix #2208.

### What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Related Tickets & Documents

https://github.com/anyproto/anytype-swift/issues/2208

### Mobile & Desktop Screenshots/Recordings

https://github.com/user-attachments/assets/af37656e-3927-4e9d-bbf4-078d0fa5431f

### Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by stansidel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mgolovko** [comment]
@stansidel thank you for your help!

There are some issues that need to be improved:
- AnytypeSheet doesn't have to add DragIndicator. The screen adds it if necessary.
- The screen size should not change.
- The keyboard is not handled.
- We expect that dragging will work anywhere on the screen and will not conflict with horizontal scrolls inside the screen.



https://github.com/user-attachments/assets/a75b6aaa-5c18-4721-9880-8bc3371f842c


https://github.com/user-attachments/assets/bc7f52a6-0b1a-4b15-8c94-33400f02a8ef

**Comment by ignatovv** [comment]
I have updated issue with richer details from @mgolovko comment
image

**Comment by stansidel** [comment]
@mgolovko Thank you for reviewing my PR and making suggestions. I'll make sure to work on the improvements soon.

**Comment by stansidel** [comment]
I've made the following changes to the PR:
* Removed DragIndicator from `anytypeSheet`.
* Added DragIndicator to ObjectSettingsView.
* Fixed an issue where the bottom sheet height could change while dragging in certain cases.

I would appreciate more clarification regarding the two remaining improvements:

* **Keyboard Handling**: Could you provide more details on the expected behavior when the keyboard is visible?
* **Drag Behavior**: We expect that dragging should work anywhere on the screen without conflicting with horizontal scrolls inside the sheet. Could you explain how you envision this interaction?

To assist with comparison, I’ve recorded and attached the following:

**anytypeSheet vs. Default SwiftUI sheet Dragging Behavior:**

Recording with scrollable content inside the bottom sheet using anytypeSheet:

https://github.com/user-attachments/assets/6697e1cd-5f6a-4c3f-8fb8-b295197e4fe6

Recording with scrollable content inside the bottom sheet using the default SwiftUI sheet:

https://github.com/user-attachments/assets/e147e4ab-9de9-43f4-afbe-02eae2668594


**Dragging with Keyboard Visible:**

Recording using anytypeSheet:

https://github.com/user-attachments/assets/96cd02f2-69e0-4729-83b5-ad0339e58c3c

Recording using the default SwiftUI sheet:

https://github.com/user-attachments/assets/150cc4a4-0507-431c-979e-fc3f93f809d9

@mgolovko, could you kindly describe your expectations for the bottom sheet’s behavior in these two scenarios?

**Comment by joe-pusya** [comment]
Hey @stansidel thank you for your work! I just had a look on your implementation/comments and would like to answer on it:

About drag gesture - we would like to avoid clashing between any other gesture (taps, scrolls (ideally scrollview too) and other).
What I mean by examples:

Our `anytypeSheet` implementation problems:
1. When you finger goes down and then up - sheet closes, you should understand the direction of dragging
2. When you clash with another gesture (tap for example) `anytypeSheet` becomes non-interactive and just closes at the end
3. Scrollview inside `anytypeSheet` -> interactive doesn't work I think so
https://github.com/user-attachments/assets/9af4e7c6-2ca5-4bc6-8c69-35e0b0182f3e

SwiftUI `sheet` behaviour to compare (I didn't understand your examples with it, can you please explain what do you mean?)
https://github.com/user-attachments/assets/8f627a3c-3354-4b11-8182-2ecac4ab3c3f

**Comment by stansidel** [comment]
Hi @joe-pusya,

Thank you for your comments. I guess I used the native `sheet` incorrectly in my examples because, in my implementation, there was a visual effect of the views in the background getting narrower.

As I see in your example of the native behavior here https://github.com/user-attachments/assets/8f627a3c-3354-4b11-8182-2ecac4ab3c3f, it works just like you'd expect the custom implementation to work. Could you please explain then what are the goals of using a custom implementation of the sheets over the native one as demonstrated in the video you provided?

**Comment by joe-pusya** [comment]
> Hi @joe-pusya,
> 
> Thank you for your comments. I guess I used the native `sheet` incorrectly in my examples because, in my implementation, there was a visual effect of the views in the background getting narrower.
> 
> As I see in your example of the native behavior here https://github.com/user-attachments/assets/8f627a3c-3354-4b11-8182-2ecac4ab3c3f, it works just like you'd expect the custom implementation to work. Could you please explain then what are the goals of using a custom implementation of the sheets over the native one as demonstrated in the video you provided?

It's just because of design request) The main goal is to implement floating sheet (clear space under the content and proper design like round corner and so on) with native swiftui sheet campabilities

**Comment by mgolovko** [comment]
@stansidel  Hi. Your PR has not been changed for a long time. We will have to close it in the next few days. When you want to publish the final decision, you can reopen the PR or create a new one

**Comment by stansidel** [comment]
Thank you for your collaboration on this PR. Unfortunately, this issue demands more time from me than I can allocate.

Regrettably, I must close the PR. I sincerely hope someone will have the chance to address and resolve this issue for you.

**Pull request closed without merging**
