### PR TITLE
Create Localizable.stringsdict

### PR DESCRIPTION
**Pull request by holton-jiang**
---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [x] 🔥 Performance Improvements
- [ ] ✅ Test
- [x] 🤖 Build
- [ ] 🔁 CI

### Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by holton-jiang** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mgolovko** [comment]
Hello @holton-jiang. Yesterday we launch Mobile Localization project.  Now we take all localization from [crowdin](https://github.com/orgs/anyproto/discussions/93). Please add your localization changes there.

https://github.com/orgs/anyproto/discussions/93
https://community.anytype.io/t/mobile-localization/11255

**Comment by mgolovko** [comment]
I see, you copied the stringdict file. In develop this file already [created](https://github.com/anyproto/anytype-swift/tree/develop/Anytype/Resources/Strings/zh-Hans.lproj)

**Comment by holton-jiang** [comment]
> Hello @holton-jiang. Yesterday we launch Mobile Localization project. Now we take all localization from [crowdin](https://github.com/orgs/anyproto/discussions/93). Please add your localization changes there.
> 
> https://github.com/orgs/anyproto/discussions/93 https://community.anytype.io/t/mobile-localization/11255

Thank you.

**Pull request closed without merging**
