### PR TITLE
Create InfoPlist.strings, Chinese Simplified translation

### PR DESCRIPTION
**Pull request by holton-jiang**
Chinese Simplified translation

---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [x] 🔥 Performance Improvements
- [ ] ✅ Test
- [x] 🤖 Build
- [x] 🔁 CI

### Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### [optional] Are there any post-deployment tasks we need to perform?

- [x] I have read the CLA Document and I hereby sign the CLA

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by mgolovko** [comment]
@holton-jiang please sign [Contributor License Agreement](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

https://github.com/anyproto/anytype-swift/pull/309#issuecomment-1702952005

**Comment by holton-jiang** [comment]
> **CLA Assistant Lite bot:CLA 助手精简版机器人：** Thank you for your pull request, we really appreciate it!感谢您的拉取请求，我们非常感谢！Please sign our [Contributor License Agreement](https://github.com/anyproto/.github/blob/main/docs/CLA.md) before we can accept your contribution.请先签署我们的贡献者许可协议，然后我们才能接受您的贡献。You can sign the CLA by simply commenting on this pull request with the following text.只需使用以下文本对此拉取请求进行注释即可对 CLA 进行签名。
> 
> I have read the CLA Document and I hereby sign the CLA我已阅读CLA文件，并特此签署CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

- [x] I have read the CLA Document and I hereby sign the CLA

**Comment by holton-jiang** [comment]
> **CLA Assistant Lite bot:** Thank you for your pull request, we really appreciate it!Please sign our [Contributor License Agreement](https://github.com/anyproto/.github/blob/main/docs/CLA.md) before we can accept your contribution.You can sign the CLA by simply commenting on this pull request with the following text.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

- [x] I have read the CLA Document and I hereby sign the CLA
- Holton.Jiang@Gmail.com

**Comment by holton-jiang** [comment]
> @holton-jiang please sign [Contributor License Agreement](https://github.com/anyproto/.github/blob/main/docs/CLA.md)
> 
> [#309 (comment)](https://github.com/anyproto/anytype-swift/pull/309#issuecomment-1702952005)

How do I sign a CLA?

**Comment by holton-jiang** [comment]
> @holton-jiang please sign [Contributor License Agreement](https://github.com/anyproto/.github/blob/main/docs/CLA.md)
> 
> [#309 (comment)](https://github.com/anyproto/anytype-swift/pull/309#issuecomment-1702952005)

I don't know how to sign the CLA, can I merge it directly?

**Comment by holton-jiang** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request closed without merging**
