### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by harley**
---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/open/blob/main/templates/CLA.md)

---

### Description

Fix typo "Crete" in the tooltip above the Create Object button.

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by harley** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mgolovko** [comment]
@harley hello! Please fix only English localization. Other localizations synced through crowndin every day.

**Comment by harley** [comment]
Thanks @mgolovko. Updated!

**Comment by mgolovko** [comment]
> Thanks @mgolovko. Updated!

You lost the changes in `en.lproj/Localizable.strings` file)

**Comment by harley** [comment]
My bad! Updated and rebased on top of latest develop @mgolovko

**Review by mgolovko — APPROVED** [review]

**Comment by fuksman** [comment]
@any contributor @harley l10n

**Pull request merged**
